import Banner from 'components/Banner';
import Header from 'components/Header';
import Post from 'components/Post';
import { sanityClient } from 'lib/sanity';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Post as IPost } from 'typing';
interface Props {
	posts: [IPost];
}
const Home: NextPage<Props> = ({ posts }: Props) => {
	return (
		<div className='max-w-7xl m-auto'>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Banner />
			<div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6'>
				{posts.map((post) => (
					<Post key={post.slug} post={post} />
				))}
			</div>
		</div>
	);
};
export const getServerSideProps = async () => {
	const query = `
	*[_type=="post" ]  | order(publishedAt desc) {
	_id,
	body,
	title,
	'date': publishedAt,
	'slug': slug.current,
	'coverImage': mainImage,
	'author': author->{name, 'picture': image.asset->url},
	}`;
	const posts = await sanityClient.fetch(query);
	return {
		props: {
			posts,
		},
	};
};
export default Home;
